name: Build LaTeX Project

on:
  workflow_dispatch:
    inputs:
      artifact_name:
        description: "Name of the generated PDF artifact"
        required: true
        default: "master-project-latex-pdf"
        type: string

jobs:
  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Compile LaTeX Project
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

      - name: Verify generated PDF
        run: |
          if [ ! -f main.pdf ]; then
            echo "ERROR: main.pdf was not generated."
            exit 1
          fi

          echo "main.pdf generated successfully."

      - name: Upload main.pdf
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: main.pdf
          if-no-files-found: error